services:
  django:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: talkit-server
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=talkit_db
      - DB_USER=sudeis
      - DB_PASSWORD=BMB8DB4L9RQ@s
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server:/app

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: talkit-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_GITHUB_CLIENT_ID=${NEXT_PUBLIC_GITHUB_CLIENT_ID}
    depends_on:
      - django
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
  
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: talkit_db
      POSTGRES_USER: sudeis
      POSTGRES_PASSWORD: BMB8DB4L9RQ@s
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sudeis -d talkit_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: